<?php
if (!isset($this->noLayout)):
    echo $this->partial('partials/title.phtml', array(
        'title' => $this->model->getOption('title')
    ));
endif;
?>
<div class="topButtons">
    <?php
    if (isset($this->buttons['add'])):
        echo $this->partial('partials/btAdicionar.phtml', array(
            'controller' => $this->controller,
            'module' => $this->module,
            'message' => $this->model->getOption('buttons', 'add')
        ));
    endif;
    ?>
</div>
<div id="formSearch" class="ui-widget-header">
    <form id="SearchForm">
        <label> Buscar: <input type="text" name="busca" id="busca" value="<?php echo $this->model->_searchWord; ?>" /></label>
        <button type="submit">Buscar</button>
    </form>
</div>
<div id="searchList">
    <?php
    echo $this->partial('default/busca.phtml', array(
        'module' => $this->module,
        'controller' => $this->controller,
        'model' => $this->model,
        'actions' => $this->actions,
        'buttons' => $this->buttons
    ));
    ?>
</div>
<?php if (isset($this->modal)): ?>
    <div id="<?php echo $this->controller; ?>Modal" class="modal" title="<?php echo $this->model->getOption('title'); ?>"></div>
    <script>
        $().submodulo({
            controller: '<?php echo $this->controller; ?>',
            module: '<?php echo $this->module; ?>',
            modal: '#<?php echo $this->controller; ?>Modal',
            form: '#<?php echo $this->form->getId(); ?>',
            parent_id : '<?php echo (!empty($this->data['parent_id'])) ? $this->data['parent_id'] : ''; ?>'
        });
        $('#<?php echo $this->controller; ?>Modal').dialog({
            beforeClose: function( event, ui ) {
                location.reload(true);
            }
        });
    </script>
<?php endif; ?>
<script src="/js/jquery.ajaxmanager.js"> </script>
<script>
    $(function(){
        var ajaxManager = $.manageAjax.create('busca',{
            queue: 'clear',
            maxRequests: 1,
            abortOld: false,
            cacheResponse: true,
            beforeSend: function(){
                $('#searchList').html(carregando);
            },
            success: function(data){
                $('#searchList').html(data);
            }
        });
        /*
         $('#busca').keyup(function(){
            $('#searchList').html(carregando);
            ajaxManager.add({
                url: "/<?php echo $this->module; ?>/<?php echo $this->controller; ?>/busca/?busca="+$('#busca').val()
            });
        });
         */
        $('#SearchForm').submit(function(event){
            ajaxManager.add({
                url: "/<?php echo $this->module; ?>/<?php echo $this->controller; ?>/busca/?busca="+$('#busca').val()
            });
            return false;
        });

        $(".pagination .botao").live('click', function(){
            var href = $(this).attr('href');
            ajaxManager.add({
                url: href
            });
            return false;
        });
    });
</script>