<?php
if (!($this->noLayout)):
    echo $this->partial('partials/title.phtml', array(
        'title' => $this->model->getOption('title')
    ));
endif;
if (isset($this->model->_addButton)):
    echo $this->partial('partials/btAdicionar.phtml', array(
        'controller' => $this->controller,
        'module' => $this->module,
        'message' => $this->model->getOption('buttons', 'add')
    ));
endif;
?>
<div id="calendar"></div>
<div id="<?php echo $this->controller; ?>Modal" class="modal" title="<?php echo $this->model->getOption('title'); ?>"></div>
<script type="text/javascript">
    $(function () {
        $('#calendar').fullCalendar({
            theme: true,
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            editable: true,
            events: "/<?php echo $this->module; ?>/Agenda/eventos/",
            buttonText: {
                today: 'Hoje',
                month: 'Mensal',
                week: 'Semanal',
                day: 'Diário'
            },
            editable: false,
                    disableDragging: true,
            disableResizing: true,
            columnFormat: {
                month: 'dddd',
                week: 'dddd MMMM/dd',
                day: 'dddd MMMM/dd'
            },
            monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
            dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
            dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
            firstDay: 1,
            timeFormat: 'H(:mm)',
            eventClick: function (calEvent, jsEvent, view) {
                window.open('<?php echo '/' . $this->module . '/' . $this->controller . '/formulario/'; ?>'+calEvent.id);
                return false;
            }
        });
    });
</script>