<div id="content">
    <div class="titulo">
        <div class="container_12">
            <div class="grid_12">
                <h1 class="institucional">Institucional</h1>
            </div>
        </div>
    </div>
    <div class="clear-fix"></div>
    <div class="container_12">
        <div class="grid_7 indent">
            <p>Fundada no ano de 2008, com objetivo de oferecer soluções ambientais, sendo na coleta, tratamento e transporte, de efluentes domésticos e industriais, a Acquasana conta com estrutura para que estes efluentes sejam destinados de acordo com as leis ambientais vigentes. Possuímos estação de tratamento própria, juntamente com uma equipe de profissionais especializados, pois acreditamos em uma tendência mundial de preservação ambiental, na qual atitudes ecologicamente corretas não só agregam valor competitivo às empresas, mas também evidenciam a responsabilidade ambiental e a coletividade, para a preservação de nosso meio ambiente.</p>
        </div>
        <div class="grid_4 prefix_1">
            <image src="/css/images/institucional.png" />
        </div>
    </div>
</div>