<?php
if (!isset($this->noLayout)):
    echo $this->partial('partials/title.phtml', array(
        'title' => $this->model->getOption('title')
    ));
endif;
?>

<div id="EmpresasTabs">
    <ul>
        <li><a href="#Dados">Dados</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Empresas-Arquivos/empresa//<?php echo $this->data['id']; ?>">Arquivos</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Empresas-Arquivos/contador//<?php echo $this->data['id']; ?>">Arquivos para o contador</a></li>
    </ul>
    <div id="Dados">
        <div class="grid_12">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $("#EmpresasTabs").tabs({
            spinner: carregando,
            ajaxOptions: {
                error: function (xhr, status, index, anchor) {
                    if (status == 'error') {
                        $(anchor.hash).html('Erro ao carregar o conteúdo');
                    } else {
                        $(anchor.hash).html(carregando);
                    }
                }
            }
<?php echo (empty($this->data['id'])) ? ', disabled: [1,2]' : ''; ?>
        });
    });
</script>