<?php
$configs = Zend_Registry::get('application');
$dominio = $configs->cliente->dominio;
?>
<div class="grid_12">
    <table class="listagem margemB">
        <tr>
            <th colspan="3"><h3>Arquivos</h3></th>
        </tr>
        <tr>
            <th>XML</th>
            <?php if (isset($this->xml)): ?>
                <td colspan="2"><a href="/<?php echo $this->xml; ?>?nocache=<?php echo date('U'); ?>" target="_blank">Download</a></td>
            <?php else: ?>
                <td colspan="2"><div class="empty">XML não gerado</div></td>
            <?php endif; ?>
        </tr>
        <tr>
            <th>PDF</th>
            <?php if (isset($this->pdf)): ?>
                <td colspan="2"><a href="/<?php echo $this->pdf; ?>?nocache=<?php echo date('U'); ?>" target="_blank">Download</a></td>
            <?php else: ?>
                <td colspan="2"><div class="empty">PDF não gerado</div></td>
            <?php endif; ?>
        </tr>
        <tr>
            <th>Faturas</th>
            <?php if (isset($this->faturas)): ?>
                <td><a href="/<?php echo $this->faturas; ?>?nocache=<?php echo date('U'); ?>" target="_blank">Download</a></td>
            <?php else: ?>
                <td><div class="empty">PDF não gerado</div></td>
            <?php endif; ?>
            <td><button type="button" class="gera_pdf" arquivo="Faturas_Acqualife_<?php echo $this->data['id']; ?>.pdf" pasta="cte/" url="http://<?php echo $dominio; ?>/erp/print/Boleto-Itau/cte-acqualife/<?php echo base64_encode($this->data['id']); ?>">Gerar PDF</button></td>
        </tr>
        <?php
        if (!empty($this->arquivosOs)):
            foreach ($this->arquivosOs AS $arquivo):
                ?>
                <tr>
                    <th>Relatório OS - <?php echo $arquivo['id']; ?></th>
                    <?php if (isset($arquivo['existe'])): ?>
                        <td><a href="/<?php echo $arquivo['arquivo']; ?>?nocache=<?php echo date('U'); ?>" target="_blank">Download</a></td>
                    <?php else: ?>
                        <td><div class="empty">PDF não gerado</div></td>
                    <?php endif; ?>
                    <td><button type="button" class="gera_pdf" arquivo="<?php echo $arquivo['file']; ?>" pasta="ordem-servico/" url="http://<?php echo $dominio; ?>/erp/print/Ordens-Servico/relatorio/<?php echo $arquivo['id']; ?>">Gerar PDF</button></td>
                </tr>
                <?php
            endforeach;
        endif;
        ?>

        <tr>
            <th colspan="3"><h3>Preview</h3></th>
        </tr>
        <tr>
            <th>XML</th>
            <?php if (isset($this->xmlpreview)): ?>
                <td colspan="2"><a href="/<?php echo $this->xmlpreview; ?>" target="_blank">Download</a></td>
            <?php else: ?>
                <td colspan="2"><div class="empty">XML não gerado</div></td>
            <?php endif; ?>
        </tr>
        <tr>
            <th>PDF</th>
            <?php if (isset($this->pdfpreview)): ?>
                <td colspan="2"><a href="/<?php echo $this->pdfpreview; ?>" target="_blank">Download</a></td>
            <?php else: ?>
                <td colspan="2"><div class="empty">PDF não gerado</div></td>
            <?php endif; ?>
        </tr>
        <tr>
            <th colspan="3"><button type="button" id="enviarArquivos" source="<?php echo $this->data['id']; ?>">Enviar Arquivos por E-mail</button></th>
        </tr>
    </table>
</div>

<div id="<?php echo $this->controller; ?>ModalArquivos" class="modal" title="Enviar arquivos do CT-e por e-mail"></div>
<script>
    $(function() {
        $('#<?php echo $this->controller; ?>ModalArquivos').dialog({
            modal: true,
            autoOpen: false,
            show: "slide",
            hide: "slide",
            width: '600',
            close: function() {
                $('#CtesTabs').tabs("load", $('#CtesTabs').tabs('option', 'selected'));
                $("#<?php echo $this->controller; ?>Modal").html('');
            }
        });
        $('.gera_pdf').die('click').unbind('click').click(function() {
            var url = $(this).attr('url');
            var pasta = $(this).attr('pasta');
            var arquivo = $(this).attr('arquivo');
            $.ajax({
                url: '/erp/Index/mpdf',
                type: 'POST',
                data: {url: url, pasta: pasta, arquivo: arquivo}
            }).done(function(msg) {
                $("#<?php echo $this->controller; ?>Modal").html(msg);
                $("#CtesTabs").tabs("load", $("#CtesTabs").tabs('option', 'selected'));
            });
        });
        $("#EnviarArquivosForm").die('submit').unbind('submit').live('submit', function() {
            $(this).ajaxSubmit({
                url: '/<?php echo $this->module; ?>/submodulo/<?php echo $this->controller; ?>/formenviararquivos/',
                success: function(msg) {
                    $("#<?php echo $this->controller; ?>ModalArquivos").html(msg).dialog('close');
                }
            });
            return false;
        });
        $('#enviarArquivos').unbind('click').die('click').click(function() {
            var source = $(this).attr('source');
            $.ajax({
                type: 'GET',
                url: "/<?php echo $this->module; ?>/submodulo/<?php echo $this->controller; ?>/formenviararquivos/",
                data: {'cte_id': source},
                success: function(data) {
                    $("#<?php echo $this->controller; ?>ModalArquivos").html(data).dialog('open');
                }
            });
            return false;
        });
    });
</script>