<p><b>Nome:</b> <?php echo $this->conteudo['nome']; ?></p>
<p><b>E-mail:</b> <?php echo $this->conteudo['email']; ?></p>
<p><b>Telefone:</b> <?php echo $this->conteudo['telefone']; ?></p>
<p><b>Cidade:</b> <?php echo $this->conteudo['cidade']; ?></p>
<p><b>Estado:</b> <?php echo $this->conteudo['estado']; ?></p>
<p><?php echo nl2br($this->conteudo['mensagem']); ?></p>
<br />
<p>-------------------------------------------------------------</p>
<p>E-mail enviado em <?php echo date('d/m/Y H:i:s'); ?>!</p>