<h2><?php echo $this->model->getOption('title'); ?></h2>
<div class="hidden">
    <form method="post" id="Form_Relatorio_Atendimento">
        <table class="listagem">
            <tr>
                <th>Data Inicial</th>
                <th><input type="text" name="data_inicial" value="<?php echo $this->data['data_inicial']; ?>" class="filter date" /></th>
                <th>Data Final</th>
                <th><input type="text" name="data_final" value="<?php echo $this->data['data_final']; ?>" class="filter date" /></th>
                <th rowspan="10">
                    <button type="submit">Filtrar</button><br /><br />
                    <button type="button" id="btImprimir">Imprimir</button>
                    <!--<th rowspan="2"><button type="button" id="btSalvaPdf">Salvar em PDF</button></th>-->
                </th>
            </tr>
            <tr>
                <th>Status</th>
                <th><select name="status">
                        <option value="">Todos</option>
                        <?php foreach ($this->model->listOptions('status') AS $key => $c): ?>
                            <option value="<?php echo $key; ?>" <?php echo ($this->data['status'] == $key) ? 'selected="selected"' : ''; ?>><?php echo $c; ?></option>
                        <?php endforeach; ?>
                    </select></th>
                <th>Funcionário</th>
                <th><select name="usuario_id">
                        <option value="">Todos</option>
                        <?php
                        $UsuariosModel = new Usuarios_Model();
                        foreach ($UsuariosModel->fetchPair() as $id => $nome):
                            ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['usuario_id'] == $id) ? 'selected:"selected"' : ''; ?>><?php echo $nome; ?></option>
                        <?php endforeach; ?>
                    </select></th>
            </tr>
            <tr>
                <th>Cliente</th>
                <th colspan="3"><select name="cliente_id">
                        <option value="">Todos</option>
                        <?php
                        $ClientesModel = new Clientes_Model();
                        foreach ($ClientesModel->fetchPair() AS $id => $nome):
                            ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['cliente_id'] == $id) ? 'selected="selected"' : ''; ?>><?php echo $nome; ?></option>
                        <?php endforeach; ?>
                    </select></th>
            </tr>
        </table>
    </form>
</div>
<?php if (!empty($this->items)): ?>
    <div class="print">
        <table class="listagem">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Data</th>
                    <th>Cliente</th>
                    <th>Descrição</th>
                    <th>Funcionário</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->items AS $item):
                    ?>
                    <tr>
                        <td align="center"><?php echo $this->model->getOption('status', $item['status']); ?></td>
                        <td align="center"><?php echo WS_Date::adjustToView($item['data']); ?></td>
                        <td><a class="buttonLink hidden" target="_blank" href="/<?php echo $this->module; ?>/Clientes/formulario/<?php echo $item['cliente_id']; ?>" title="<?php echo $ClientesModel->getOption('buttons', 'go'); ?>"><?php echo $ClientesModel->getOption('buttons', 'go'); ?></a> <?php echo $item['cliente']; ?></td>
                        <td align="center"><?php echo nl2br($item['descricao']); ?></td>
                        <td><?php echo $item['nome']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <script type="text/javascript">
        $(function(){
            $("#btSalvaPdf").click(function(){
                var form = $("#Form_Relatorio_Atendimento");
                form.attr("target","_blank").attr("action",'/<?php echo $this->module; ?>/save/Relatorio-Atendimentos/pdf/');
                form.submit();
                form.attr("target","_self").attr("action",'');
            });
        });
    </script>
    <?php
else:
    ?>
    <div class="empty">
        Nenhum dado filtrado
    </div>
<?php endif; ?>