<?php
if (!($this->noLayout)):
    echo $this->partial('partials/title.phtml', array(
        'title' => $this->model->getOption('title')
    ));
endif;
?>
<?php if (!empty($this->items)): ?>
    <table class="listagem" id="LogsAlteracoesListagem">
        <thead>
            <tr>
                <th></th>
                <th>Data</th>
                <th>Usuário</th>
                <th>Ação</th>
                <th>IP</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->items AS $item):
                $item = $this->model->adjustToView($item);
                ?>
                <tr>
                    <td><button class="btVisualizar" source="<?php echo $item['id']; ?>">Visualizar Log</button></td>
                    <td><?php echo $item['created']; ?></td>
                    <td><?php echo $item['nome']; ?></td>
                    <td><?php echo $item['acao']; ?></td>
                    <td><?php echo $item['ip']; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php
else:
    echo $this->partial('partials/empty.phtml', array(
        'message' => $this->model->getOption('messages', 'empty')
    ));
endif;
?>
<div id="logsModal" class="modal" title="Logs de Alterações"></div>
<script type="text/javascript">
    $(function(){
        $('#LogsAlteracoesListagem').dataTable({
            "oLanguage": { "sUrl": "/js/dataTables/pt_BR.txt" },
            "bJQueryUI": true,
            "aaSorting": [[1,"desc"]],
            "aoColumns":[
                {"bSortable": false},
                {"bSortable": true, "sType": "date-euro"},
                {"bSortable": true},
                {"bSortable": false},
                {"bSortable": false}
            ]
        });
        $('.btVisualizar').button({
            'icons':{
                primary:'ui-icon-search'
            },
            'text': false
        }).click(function(){
            $.get('<?php echo '/' . $this->module . '/submodulo/' . $this->controller . '/dados/'; ?>'+$(this).attr('source'), function(data){
                $('#logsModal').html(data).dialog('open');
            });
        });
        $('#logsModal').die('dialog').unbind('dialog').dialog({
            modal: true,
            autoOpen: false,
            show: "slide",
            hide: "slide",
            width: '600'
        });
    });
</script>