<?php echo $this->form; ?>
<script>
    $(function() {
        $("#assunto_template").change(function() {
            var id = $(this).select().val();
            $.ajax({
                url: '/<?php echo $this->module; ?>/submodulo/Textos/pegatexto/' + id,
                datatype: 'GET',
                success: function(data) {
                    if (data != "")
                        $("#assunto").val(data);
                }
            });
        });
        $("#mensagem_template").change(function() {
            var id = $(this).select().val();
            $.ajax({
                url: '/<?php echo $this->module; ?>/submodulo/Textos/pegatexto/' + id,
                datatype: 'GET',
                success: function(data) {
                    if (data != "")
                        $("#mensagem").val(data);
                }
            });
        });
    });
</script>