<h2>Relatório de Fluxo de Caixa</h2>
<?php
if ($this->csv) :
    ?>
    <script>
        $(function () {
            $.jGrowl("Verifique o bloqueio de pop-ups!", {theme: "warning", life: 10000});
        });
        window.open('/uploads/relatorios/<?php echo $this->csv; ?>');
    </script>
    <?php
endif;
?>
<form method="POST">
    <table class="listagem hidden margemB">
        <tr>
            <th colspan="4">Data inicial</th>
            <th colspan="4">Data final</th>
            <th colspan="4">Empresa</th>
            <th rowspan="2"><button type="submit">Filtrar</button></th>
            <th rowspan="2"><button type="button" id="btImprimir">Imprimir</button></th>
            <th rowspan="2"><button type="button" id="btExportarCSV">Exportar em CSV</button>
                <input type="checkbox" class="invisivel" name="gera_csv" id="gera_csv" /></th>
        </tr>
        <tr>
            <th>Mês</th>
            <th><select name="dataInicial[mes]" class="ui-corner-all mes">
                    <?php for ($i = 1; $i < 13; $i++): ?>
                        <option value="<?php echo substr('0' . $i, -2); ?>" <?php echo ($this->data['dataInicial']['mes'] == $i) ? 'selected="selected"' : ''; ?>><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
            </th>
            <th>Ano</th>
            <th><select name="dataInicial[ano]" class="ui-corner-all filter ano">
                    <?php for ($i = 2000; $i <= 2020; $i++): ?>
                        <option value="<?php echo $i; ?>" <?php echo ($this->data['dataInicial']['ano'] == $i) ? 'selected="selected"' : ''; ?>><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
            </th>
            <th>Mês</th>
            <th><select name="dataFinal[mes]" class="ui-corner-all mes">
                    <?php for ($i = 1; $i < 13; $i++): ?>
                        <option value="<?php echo substr('0' . $i, -2); ?>" <?php echo ($this->data['dataFinal']['mes'] == $i) ? 'selected="selected"' : ''; ?>><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
            </th>
            <th>Ano</th>
            <th><select name="dataFinal[ano]" class="ui-corner-all filtro ano">
                    <?php for ($i = 2000; $i <= 2020; $i++): ?>
                        <option value="<?php echo $i; ?>" <?php echo ($this->data['dataFinal']['ano'] == $i) ? 'selected="selected"' : ''; ?>><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
            </th>
            <th>Empresa</th>
            <th>
                    <?php
                    $empresas = Empresas_Model::fetchPair();
                    foreach ($empresas AS $id => $nome):
                        ?>
                        <p>
                            <label>
                                <input name="empresa_id[]" type="checkbox" value="<?php echo $id; ?>" <?php echo (in_array($id, $this->data['empresa_id'])) ? 'checked="checked"' : ''; ?> /> <?php echo $nome; ?>
                            </label>
                        </p>
                        <?php
                    endforeach;
                    ?>
            </th>
        </tr>
    </table>
</form>
<?php
if (!empty($this->contas) || !empty($this->contasReceberCategorizadas) || !empty($this->contasCategorizadas)):
    $WM = new WS_Money();
    $periodoInicial = new Zend_Date($this->data['dataInicial']['ano'] . '-' . $this->data['dataInicial']['mes'] . '-01');
    $periodoFinal = new Zend_Date($this->data['dataFinal']['ano'] . '-' . $this->data['dataFinal']['mes'] . '-01');
    $total = array('recebido' => 0, 'pago' => 0, 'saldo' => 0);
    ?>
    <h2>Período Apurado [<?php echo $periodoInicial->toString('MM/yyyy') . ' - ' . $periodoFinal->toString('MM/yyyy'); ?>]</h2>
    <div id="grafico" style="width: 700px; margin:0 auto;"></div>
    <?php if (!empty($this->contas)): ?>
        <table class="listagem">
            <thead>
                <tr>
                    <td>Mês/Ano</td>
                    <th>Recebido</th>
                    <th>Pago</th>
                    <th>Saldo</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->contas AS $conta):
                    $saldo = $conta['contas_receber'] - $conta['contas_pagar'];
                    $total['recebido'] += $conta['contas_receber'];
                    $total['pago'] += $conta['contas_pagar'];
                    $total['saldo'] += $conta['saldo'];
                    ?>
                    <tr>
                        <th><?php echo $conta['legenda']; ?></th>
                        <td class="valor"><?php echo WS_Money::adjustToView($conta['contas_receber']); ?></td>
                        <td class="valor"><?php echo WS_Money::adjustToView($conta['contas_pagar']); ?></td>
                        <td class="valor"><?php echo WS_Money::adjustToView($conta['saldo']); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <th>Total</th>
                    <th><?php echo WS_Money::adjustToView($total['recebido']); ?></th>
                    <th><?php echo WS_Money::adjustToView($total['pago']); ?></th>
                    <th><?php echo WS_Money::adjustToView($total['saldo']); ?></th>
                </tr>
            </tfoot>
        </table>
        <?php
    endif;
    $tot = $total;
    if($tot['pago'] == 0):
        $tot['pago'] = 1;
    endif;
    $total = array('liquido' => $tot['recebido'], 'saldo' => $tot['recebido']);
    if (!empty($this->contasReceberCategorizadas)):
        ?>
        <br class="clear margemB" />
        <h2>Contas a Receber - Detalhamento por categoria</h2>
        <table class="listagem">
            <thead>
                <tr>
                    <th>Categoria de Cliente</th>
                    <th>% do Recebido</th>
                    <th>Recebido (<?php echo WS_Money::adjustToView($tot['recebido']); ?>)</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->contasReceberCategorizadas AS $conta):
                    $porcentagem = $conta['total'] * 100 / $tot['recebido'];
                    ?>
                    <tr>
                        <td><?php echo $conta['categoria']; ?></td>
                        <td align="center"><?php echo WS_Money::adjustToDb($porcentagem); ?>%</td>
                        <td align="center"><?php echo WS_Money::adjustToView($conta['total']); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php
    endif;
    $total = array('liquido' => $tot['pago'], 'saldo' => $tot['pago']);
    if (!empty($this->contasCategorizadas)):
        ?>
        <br class="clear margemB" />
        <h2>Contas a Pagar - Detalhamento por categoria</h2>
        <table class="listagem">
            <thead>
                <tr>
                    <th>Categoria de Conta</th>
                    <th>% do Pago</th>
                    <th>Pago (<?php echo WS_Money::adjustToView($tot['pago']); ?>)</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->contasCategorizadas AS $conta):
                    $porcentagem = $conta['total'] * 100 / $tot['pago'];
                    ?>
                    <tr>
                        <td><?php echo $conta['categoria']; ?></td>
                        <td align="center"><?php echo WS_Money::adjustToDb($porcentagem); ?>%</td>
                        <td align="center"><?php echo WS_Money::adjustToView($conta['total']); ?></td>
                    </tr>
        <?php endforeach; ?>
            </tbody>
        </table>
        <?php
    endif;
    ?>
    <script type="text/javascript">
        google.load("visualization", "1", {packages: ["corechart"]});
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Ano');
            data.addColumn('number', 'Recebido');
            data.addColumn('number', 'Pago');
            data.addRows([
    <?php foreach ($this->contas AS $conta): ?>
                    ['<?php echo $conta['legenda']; ?>', <?php echo $conta['contas_receber']; ?>, <?php echo $conta['contas_pagar']; ?>],
    <?php endforeach; ?>
            ]);

            var chart = new google.visualization.ColumnChart(document.getElementById('grafico'));
            chart.draw(data, {width: 700, height: 400, title: 'Fluxo de Caixa', colors: ['green', 'red'],
                hAxis: {title: 'Ano'}, vAxis: {title: 'Valor'}

            });
        }
    </script>
<?php else: ?>
    <div class="empty">
        Nenhum dado filtrado
    </div>
<?php endif; ?>