<div id="mapa"></div>
<script>
    var map;
    function initMap() {
        map = new google.maps.Map(document.getElementById("mapa"), {
            center: {lat: -29.1715253, lng: -51.5168625},
            zoom: 17
        });
        setMarkers(map);
    }

    var markers = [
<?php
foreach ($this->enderecos AS $endereco):
    echo '["' . $endereco['razao_social'] . ' (' . $endereco['categoria'] . ')",' . $endereco['coordenadas'] . '],';
endforeach;
?>
    ];

    function setMarkers(map) {
        var image = {
            url: 'images/beachflag.png',
            size: new google.maps.Size(20, 32),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(0, 32)
        };
        var shape = {
            coords: [1, 1, 1, 20, 18, 20, 18, 1],
            type: 'poly'
        };
        for (var i = 0; i < markers.length; i++) {
            var beach = markers[i];
            var marker = new google.maps.Marker({
                position: {lat: beach[1], lng: beach[2]},
                map: map,
                //icon: image,
                shape: shape,
                title: beach[0],
//                zIndex: beach[3]
            });
        }
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6WVqwZePY3sNtYyaRrIBIFWEctsxwXbE&callback=initMap" async defer></script>

<style>
    #mapa{
        width: 100%;
        height: 900px;
    }
</style>

