<div class="grid_12">
    <?php
    if (!isset($this->noLayout)):
        echo $this->partial('partials/title.phtml', array(
            'title' => $this->model->getOption('title')
        ));
    endif;
    echo $this->partial('partials/btAdicionar.phtml', array(
        'controller' => $this->controller,
        'module' => $this->module,
        'message' => $this->model->getOption('buttons', 'add')
    ));
    ?>
    <div class="modal" id="ClientesEnderecosModal" title="<?php echo $this->model->getOption('title'); ?>"></div>
    <?php if (!empty($this->items)): ?>
        <table class="listagem">
            <thead>
                <tr class="ui-widget-header">
                    <th></th>
                    <th></th>
                    <th>Fachada</th>
                    <th>Categoria</th>
                    <th>Endereço</th>
                    <th>Bairro</th>
                    <th>Cidade</th>
                    <th>Cep</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->items AS $item):
                    $item = $this->model->adjustToView($item);
                    ?>
                    <tr>
                        <td align="center"><button class="btEditar <?php echo $this->controller; ?>" source="<?php echo $item['id']; ?>"><?php echo $this->model->getOption('buttons', 'edit'); ?></button></td>
                        <td align="center"><button class="btExcluir <?php echo $this->controller; ?>" source="<?php echo $item['id']; ?>"><?php echo $this->model->getOption('buttons', 'delete'); ?></button></td>
                        <td align="center"><?php if ($item['imagem']): ?><a href="/storage/file/<?php echo $item['imagem']; ?>/clientes-enderecos/view" target="_blank"><img src="/storage/imagem/<?php echo $item['imagem']; ?>/clientes-enderecos?w=100&h=100&c=crop" /></a><?php endif; ?></td>
                        <td><?php echo $item['categoria']; ?></td>
                        <td><?php echo $item['endereco']; ?>, <?php echo $item['numero']; ?> <?php echo $item['complemento']; ?> - <?php echo $item['uf']; ?></td>
                        <td><?php echo $item['bairro']; ?></td>
                        <td><?php echo $item['municipio']; ?></td>
                        <td><?php echo $item['cep']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php
    else:
        echo $this->partial('partials/empty.phtml', array(
            'message' => $this->model->getOption('messages', 'empty')
        ));
    endif;
    if ($this->noLayout):
        ?>
        <div id="<?php echo $this->controller; ?>Modal" class="modal" title="<?php echo $this->model->getOption('title'); ?>"></div>
        <script type="text/javascript" src="/js/submodulo.js"></script>
        <script type="text/javascript">
            $(function () {
                $().submodulo({
                    controller: '<?php echo $this->controller; ?>',
                    module: '<?php echo $this->module; ?>',
                    tab: '#ClientesTabs',
                    modal: '#<?php echo $this->controller; ?>Modal',
                    form: '#<?php echo $this->form->getId(); ?>',
                    parent_id: '<?php echo (!empty($this->data['parent_id'])) ? $this->data['parent_id'] : ''; ?>'
                });
            });
        </script>
    <?php endif; ?>
</div>