<h1>Encontramos um erro</h1>
<h2><?php echo $this->message ?></h2>
<?php if (isset($this->exception)): ?>
    <h3>Informação do erro:</h3>
    <p>
        <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
    </p>
    <h3>Mais informações:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?></pre>
    <h3>Parâmetros:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
<?php endif; ?>
