<h2><?php echo $this->model->getOption('title'); ?></h2>
<?php
if ($this->csv) :
    ?>
    <script>
        $(function () {
            $.jGrowl("Verifique o bloqueio de pop-ups!", {theme: "warning", life: 10000});
        });
        window.open('/uploads/<?php echo $this->csv; ?>');
    </script>
    <?php
endif;
?>
<div class="hidden">
    <form method="post" id="Form_Relatorio_Notas_Fiscais">
        <table class="listagem">
            <tr>
                <th>Data Inicial</th>
                <th><input type="text" name="data_inicial" value="<?php echo $this->data['data_inicial']; ?>" class="filter date" /></th>
                <th>Data Final</th>
                <th><input type="text" name="data_final" value="<?php echo $this->data['data_final']; ?>" class="filter date" /></th>
                <th rowspan="4"><button type="submit">Filtrar</button></th>
                <th rowspan="4"><button type="button" id="btImprimir">Imprimir</button></th>
                <th rowspan="4"><button type="button" id="btExportarCSV">Exportar em CSV</button>
                    <input type="checkbox" class="invisivel" name="gera_csv" id="gera_csv" /></th>
            </tr>
            <tr>
                <th colspan="2">Cliente</th>
                <?php $ClientesModel = new Clientes_Model(); ?>
                <th colspan="2"><select name="cliente_id">
                        <option value="">Todos</option>
                        <?php foreach ($ClientesModel->fetchPair() as $id => $nome): ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['cliente_id'] == $id) ? 'selected="selected"' : ''; ?>><?php echo $nome; ?></option>
                        <?php endforeach; ?>
                    </select></th>
            </tr>
            <tr>
                <th colspan="2">Tipo de Nota Fiscal</th>
                <?php $tipos = $this->model->listOptions('tipo'); ?>
                <th colspan="2"><select name="tipo">
                        <option value="">Todos</option>
                        <?php foreach ($tipos AS $key => $tipo): ?>
                            <option value="<?php echo $key; ?>" <?php echo ($this->data['tipo'] == $key) ? 'selected="selected"' : ''; ?>><?php echo $tipo; ?></option>
                        <?php endforeach; ?>
                    </select></th>
            </tr>
        </table>
    </form>
</div>
<?php if (!empty($this->items)): ?>
    <div class="print">
        <table class="listagem">
            <thead>
                <tr>
                    <th>Número</th>
                    <th>Cliente</th>
                    <th>Orçamento</th>
                    <th>Data de Emissão</th>
                    <th>Tipo</th>
                    <th>Valor</th>
                    <th>Valor Retido</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $OrcamentosModel = new Orcamentos_Model();
                $total['valor'] = 0;
                $total['retido'] = 0;
                $i = 0;
                foreach ($this->items AS $item):
                    $total['valor'] += $item['valor'];
                    $total['retido'] += $item['valor_retido'];
                    $item = $this->model->adjustToView($item);
                    $i++;
                    ?>
                    <tr>
                        <td align="center"><?php echo $item['numero']; ?> - <?php echo $i; ?></td>
                        <td><a class="buttonLink hidden" target="_blank" href="/<?php echo $this->module; ?>/Clientes/formulario/<?php echo $item['cliente_id']; ?>" title="<?php echo $ClientesModel->getOption('buttons', 'go'); ?>"><?php echo $ClientesModel->getOption('buttons', 'go'); ?></a> <?php echo $item['cliente']; ?></td>
                        <td><a class="buttonLink hidden" target="_blank" href="/<?php echo $this->module; ?>/Orcamentos/formulario/<?php echo $item['orcamento_id']; ?>" title="<?php echo $OrcamentosModel->getOption('buttons', 'go'); ?>"><?php echo $OrcamentosModel->getOption('buttons', 'go'); ?></a> <?php echo $item['orcamento_id']; ?></td>
                        <td align="center"><?php echo $item['data_geracao']; ?></td>
                        <td align="center"><?php echo $item['tipo']; ?></td>
                        <td align="center"><?php echo $item['valor']; ?></td>
                        <td align="center"><?php echo $item['valor_retido']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="5">Total</th>
                    <td align="center"><?php echo WS_Money::adjustToView($total['valor']); ?></td>
                    <td align="center"><?php echo WS_Money::adjustToView($total['retido']); ?></td>
                </tr>
            </tfoot>
        </table>
    </div>
    <?php
else:
    ?>
    <div class="empty">
        Nenhum dado filtrado
    </div>
<?php endif; ?>