<?php
if (!isset($this->noLayout)):
    echo $this->partial('partials/title.phtml', array(
        'title' => $this->model->getOption('title')
    ));
endif;
if (!empty($this->data['ordem_servico_id'])):
    ?>
    <div class="margemB">
        <a class="botao" href="/<?php echo $this->module; ?>/Ordens-Servico/formulario/<?php echo $this->data['ordem_servico_id']; ?>" target="_blank">Ir para a Ordem de Serviço</a>
        <a class="botao" href="/<?php echo $this->module . '/' . $this->controller . '/formularioimpressao/' . $this->data['id']; ?>" target="_blank">Imprimir MTR</a>
    </div>
<?php endif; ?>
<div id="MtrTabs">
    <ul>
        <li><a href="#Mtr">MTR</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Certificados/formulario//<?php echo $this->data['id']; ?>">Certificado</a></li>
    </ul>
    <div id="Mtr">
        <div class="grid_12">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#MtrTabs").tabs({
        spinner: carregando,
        ajaxOptions: {
            error: function(xhr, status,index, anchor){
                if(status == 'error'){
                    $(anchor.hash).html('Erro ao carregar o conteúdo');
                }else{
                    $(anchor.hash).html(carregando);
                }
            }
        }
<?php echo (empty($this->data['id'])) ? ', disabled: [1]' : ''; ?>
    });
</script>