<div id="content">
    <div class="titulo">
        <div class="container_12">
            <div class="grid_12">
                <h1 class="contato"> Contato</h1>
            </div>
        </div>
    </div>
    <div class="container_12">
        <div class="grid_12 wrapper" id="contato">
            <h2>Fale Conosco</h2>
            <form method="POST">
                <div class="grid_6 alpha">
                    <?php echo $this->form->nome->renderViewHelper(); ?>
                    <?php echo $this->form->email->renderViewHelper(); ?>
                    <?php echo $this->form->telefone->renderViewHelper(); ?>
                    <?php echo $this->form->cidade->renderViewHelper(); ?>
                    <?php echo $this->form->estado->renderViewHelper(); ?>
                    <br />* Campos obrigatórios
                    <script src='https://www.google.com/recaptcha/api.js'></script>

                    <button
class="g-recaptcha"
data-sitekey="6LcScFgUAAAAAIke6uHutdp-01Vcy48yqZn4KBHV"
data-callback="YourOnSubmitFn">
Submit
</button>
                </div>
                <div class="grid_6 omega">
                    <?php echo $this->form->mensagem->renderViewHelper(); ?>
                    <button>Enviar</button>
                </div>
            </form>
        </div>
    </div>
    <div class="clearfix"></div>
    <div id="localizacao" class="cinza">
        <div class="container_12">
            <div class="grid_3">
                <h2>Localização</h2>
            </div>
            <div class="grid_6">
                <input type="text" id="saida" placeholder="DE ONDE VOCÊ QUER CHEGAR?" />
            </div>
            <div class="grid_3">
                <button id="ComoChegar">Como Chegar</button>
            </div>
        </div>
    </div>
    <div id="mapa_canvas"></div>
    <script>
        $(function() {
            $('#ComoChegar').unbind('click').die('click').click(function() {
                var saida = $('#saida').val();
                if (saida != '') {
                    window.open('https://www.google.com.br/maps/dir/' + saida + '/ACQUASANA+TRASNPORTE+E+TRATAMENTO+DE+EFLUENTES+-+R.+Tr%C3%AAs+de+Outubro,+40,+Bento+Gon%C3%A7alves+-+RS,+95700-000/@-29.1658821,-51.5136461,16z/?hl=pt-BR', '_blank');
                }
            });
        });
    </script>
</div>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true"></script>
<script type="text/javascript">
        function carregaMapa() {
            var latLang = new google.maps.LatLng(-29.17160, -51.51691);
            var Options = {
                zoom: 16,
                center: latLang,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            map = new google.maps.Map(document.getElementById('mapa_canvas'), Options);

            var marker = new google.maps.Marker({
                position: latLang,
                map: map,
                title: 'Acquasana - Tratamento de Efluentes',
                clickable: false,
                icon: 'css/images/marker.png'
            });
        }
        google.maps.event.addDomListener(window, 'load', carregaMapa);
</script>
<style>
    #mapa_canvas{
        width: 100%;
        height: 450px;
        margin-bottom: 30px;
    }
</style>