<?php
if (!($this->noLayout)):
    echo $this->partial('partials/title.phtml', array(
        'title' => $this->model->getOption('title')
    ));
endif;
if (!empty($this->data['data_pagamento']) && 1 != 1):
    $item = $this->data;
    ?>
    <table class="listagem">
        <tbody>
            <tr>
                <th>Orçamento</th>
                <td><?php echo $item['orcamento_id']; ?></td>
            </tr>
            <tr>
                <th>Empresa</th>
                <td><?php echo $item['empresa']; ?></td>
            </tr>
            <tr>
                <th>Cliente</th>
                <td><?php echo $item['cliente']; ?></td>
            </tr>
            <tr>
                <th>Data de Vencimento</th>
                <td><?php echo $item['data_vencimento']; ?></td>
            </tr>
            <tr>
                <th>Valor</th>
                <td><?php echo $item['valor']; ?></td>
            </tr>
            <tr>
                <th>Forma de Pagamento</th>
                <td><?php echo $item['forma_pagamento']; ?></td>
            </tr>
            <tr>
                <th>Data de Pagamento</th>
                <td><?php echo $item['data_pagamento']; ?></td>
            </tr>
            <tr>
                <th>Valor Pago</th>
                <td><?php echo $item['valor_pago']; ?></td>
            </tr>
        </tbody>
    </table>
    <div class="empty">
        Essa conta ja foi paga e não pode ser alterada.
    </div>
    <button onclick="javascript: history.back() ;">Cancelar</button>
    <?php
else:
    $item = $this->data;
    ?>
    <table class="listagem">
        <tr>
            <th>Data do Vencimento</th>
            <th>Valor</th>
        </tr>
        <tr>
            <td><?php echo $item['data_vencimento']; ?></td>
            <td class="valor"><?php echo $item['valor']; ?></td>
        </tr>
    </table>
    <?php echo $this->form; ?>
<?php endif; ?>