<h2><?php echo $this->model->getOption('title'); ?></h2>
<?php
if ($this->csv) :
    ?>
    <script>
        $(function () {
            $.jGrowl("Verifique o bloqueio de pop-ups!", {theme: "warning", life: 10000});
        });
        window.open('/uploads/relatorios/<?php echo $this->csv; ?>');
    </script>
    <?php
endif;
?>
<div class="hidden">
    <form method="post" id="Form_Relatorio_OS">
        <table class="listagem">
            <tr>
                <th>Data Inicial</th>
                <th><input type="text" name="data_inicial" value="<?php echo $this->data['data_inicial']; ?>" class="filter date" /></th>
                <th>Data Final</th>
                <th><input type="text" name="data_final" value="<?php echo $this->data['data_final']; ?>" class="filter date" /></th>
                <th rowspan="10">
                    <button type="submit">Filtrar</button><br /><br />
                    <button type="button" id="btImprimir">Imprimir</button><br/><br />
                    <!--<button type="button" id="btSalvaPdf">Salvar em PDF</button><br /><br />-->
                    <button type="button" id="btSalvaXls">Relatório Fepan</button><br />
                    <button type="button" id="btExportarCSV">Exportar em CSV</button>
                    <input type="checkbox" class="invisivel" name="gera_csv" id="gera_csv" />
                </th>
            </tr>
            <tr>
                <th>Empresa</th>
                <th><select name="empresa_id">
                        <option value="">Todas</option>
                        <?php
                        $EmpresasModel = new Empresas_Model();
                        foreach ($EmpresasModel->fetchPair() AS $key => $c):
                            ?>
                            <option value="<?php echo $key; ?>" <?php echo ($this->data['empresa_id'] == $key) ? 'selected="selected"' : ''; ?>><?php echo $c; ?></option>
                        <?php endforeach; ?>
                    </select></th>
                <th>Status</th>
                <th><select name="status">
                        <option value="">Todos</option>
                        <?php foreach ($this->model->listOptions('status') AS $key => $c): ?>
                            <option value="<?php echo $key; ?>" <?php echo ($this->data['status'] == $key) ? 'selected="selected"' : ''; ?>><?php echo $c; ?></option>
                        <?php endforeach; ?>
                    </select></th>
            </tr>
            <tr>
                <th>Cliente</th>
                <th colspan="3"><select name="cliente_id">
                        <option value="">Todos</option>
                        <?php
                        $ClientesModel = new Clientes_Model();
                        foreach ($ClientesModel->fetchPair() AS $key => $c):
                            ?>
                            <option value="<?php echo $key; ?>" <?php echo ($this->data['cliente_id'] == $key) ? 'selected="selected"' : ''; ?>><?php echo $c; ?></option>
                        <?php endforeach; ?>
                    </select></th>
            </tr>
        </table>
    </form>
</div>
<?php if (!empty($this->items)): ?>
    <div class="print">
        <form action="/<?php echo $this->module. '/print/'.$this->controller.'/impressao' ?>" method="POST">
            <table class="listagem">
                <thead>
                    <tr>
                        <th></th>
                        <th>Status</th>
                        <th>Código</th>
                        <th>Data da Coleta</th>
                        <th>Cliente</th>
                        <th>Empresa</th>
                        <th>Vol. Dom.</th>
                        <th>Vol. Ind.</th>
                        <th>Transporte</th>
                        <th>Cert.</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $WD = new WS_Date();
                    $total_domestico = 0;
                    $total_industrial = 0;
                    foreach ($this->items AS $item):
                        $total_domestico += $item['volume_domestico'] = $this->model->volumeDomestico($item['id']);
                        $total_industrial += $item['volume_industrial'] = $this->model->volumeIndustrial($item['id']);
                        $total_transporte += $item['volume_transporte'] = $this->model->transporte($item['id']);
                        ?>
                        <tr>
                            <td align="center"><input type="checkbox" value="<?php echo $item['id']; ?>" name="os_id[]" class="checkbox" /></td>
                            <td align="center"><?php echo $this->model->getOption('status', $item['status']); ?></td>
                            <td align="center"><?php echo $item['orcamento_id'] . '.' . $item['sequencial']; ?></td>
                            <td align="center"><?php echo WS_Date::adjustToView($item['data_coleta']); ?></td>
                            <td><a class="buttonLink hidden" target="_blank" href="/<?php echo $this->module; ?>/Clientes/formulario/<?php echo $item['cliente_id']; ?>" title="<?php echo $ClientesModel->getOption('buttons', 'go'); ?>"><?php echo $ClientesModel->getOption('buttons', 'go'); ?></a> <?php echo $item['cliente']; ?></td>
                            <td align="center"><?php echo $item['empresa']; ?></td>
                            <td align="center"><?php echo $item['volume_domestico']; ?></td>
                            <td align="center"><?php echo $item['volume_industrial']; ?></td>
                            <td align="center"><?php echo $item['volume_transporte']; ?></td>
                            <td align="center"><?php echo ($item['certificado_id']) ? 'S' : 'N'; ?></td>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="6" align="right">Totais</th>
                        <th><?php echo $total_domestico; ?></th>
                        <th><?php echo $total_industrial; ?></th>
                        <th><?php echo $total_transporte; ?></th>
                        <th></th>
                    </tr>
                    <tr>
                        <td align="right" colspan="10"><button type="submit">Imprimir OS</button></td>
                    </tr>
                </tfoot>
            </table>
        </form>
    </div>
    <script type="text/javascript">
        $(function(){
            $("#btSalvaPdf").click(function(){
                var form = $("#Form_Relatorio_OS");
                form.attr("target","_blank").attr("action",'/<?php echo $this->module; ?>/save/Relatorio-Ordem-Servico/pdf');
                form.submit();
                form.attr("target","_self").attr("action",'');
            });
            $("#btSalvaXls").click(function(){
                var form = $("#Form_Relatorio_OS");
                form.attr("target","_blank").attr("action",'/<?php echo $this->module; ?>/save/Relatorio-Ordem-Servico/xls');
                form.submit();
                form.attr("target","_self").attr("action",'');
            });
        });
    </script>
    <?php
else:
    ?>
    <div class="empty">
        Nenhum dado filtrado
    </div>
<?php endif; ?>