<?php
if (!isset($this->noLayout)):
    $title = $this->model->getOption('title');
    if (!empty($this->data['razao_social'])):
        $title .= ' (' . $this->data['razao_social'] . ')';
    endif;
    echo $this->partial('partials/title.phtml', array(
        'title' => $title
    ));
endif;
?>
<div id="AdministradoresCondominiosTabs">
    <ul>
        <li><a href="#Dados">Dados</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Administradores-Condominios-Telefones/administrador//<?php echo $this->data['id']; ?>">Telefones</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Administradores-Crm/administrador//<?php echo $this->data['id']; ?>">Atendimentos</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Administradores-Arquivos/administrador//<?php echo $this->data['id']; ?>">Arquivos</a></li>
    </ul>
    <div id="Dados">
        <div class="grid_12">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<script>
    $(function() {
        $("#AdministradoresCondominiosTabs").tabs({
            spinner: carregando,
            ajaxOptions: {
                error: function(xhr, status, index, anchor) {
                    if (status == 'error') {
                        $(anchor.hash).html('Erro ao carregar o conteúdo');
                    } else {
                        $(anchor.hash).html(carregando);
                    }
                }
            }
<?php echo (empty($this->data['id'])) ? ', disabled: [1]' : ''; ?>
        });
    });
</script>
