<h2><?php echo $this->model->getOption('title'); ?></h2>
<div class="hidden">
    <form method="post" id="RelatorioClientesCondominiosForm">
        <table class="listagem">
            <tr>
                <th>Administrador de Condomínio</th>
                <th rowspan="10">
                    <button type="submit">Filtrar</button><br /><br />
                    <button type="button" id="btImprimir">Imprimir</button>
                </th>
            </tr>
            <tr>
                <?php $AdministradoresCondominiosModel = new AdministradoresCondominios_Model(); ?>
                <th><select name="administrador_id">
                        <option value="-1">Sem Administradores</option>
                        <?php foreach ($AdministradoresCondominiosModel->fetchPair() as $id => $nome): ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['administrador_id'] == $id) ? "selected" : ''; ?>><?php echo $nome; ?></option>
                        <?php endforeach; ?>
                    </select></th>
            </tr>
        </table>
    </form>
</div>
<?php if (!empty($this->items)): ?>
    <div class="print">
        <table class="listagem">
            <thead>
                <tr>
                    <th>Cliente</th>
                    <th>Telefones</th>
                    <th>Endereço</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $WD = new WS_Date();
                foreach ($this->items AS $item):
                    $item = $this->model->ajusteRelatorioCondominio($item);
                    ?>
                    <tr>
                        <td><a class="buttonLink hidden" target="_blank" href="/<?php echo $this->module; ?>/Clientes/formulario/<?php echo $item['id']; ?>" title="<?php echo $this->model->getOption('buttons', 'go'); ?>"><?php echo $this->model->getOption('buttons', 'go'); ?></a> <?php echo $item['razao_social']; ?></td>
                        <td><?php echo $item['telefones']; ?></td>
                        <td><?php echo $item['enderecos']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php
else:
    ?>
    <div class="empty">
        Nenhum dado filtrado
    </div>
<?php endif; ?>
