<h2><?php echo $this->model->getOption('title'); ?></h2>
<div class="hidden">
    <form method="post" id="Form_Relatorio_Atendimento">
        <table class="listagem">
            <tr>
                <th>Data Inicial</th>
                <th><input type="text" name="data_inicial" value="<?php echo $this->data['data_inicial']; ?>" class="filter date" /></th>
                <th>Data Final</th>
                <th><input type="text" name="data_final" value="<?php echo $this->data['data_final']; ?>" class="filter date" /></th>
                <th rowspan="10">
                    <button type="submit">Filtrar</button><br /><br />
                    <button type="button" id="btImprimir">Imprimir</button>
                </th>
            </tr>
        </table>
    </form>
</div>
<?php if (!empty($this->items)): ?>
    <div class="print">
        <table class="listagem">
            <thead>
                <tr>
                    <th></th>
                    <th>Cliente</th>
                    <th>Categoria</th>
                    <th>Cidade</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $i = 0;
                $ClientesModel = new Clientes_Model();
                foreach ($this->items AS $item):
                    $i++;
                    ?>
                    <tr>
                        <td><?php echo $i; ?></td>
                        <td><a class="buttonLink hidden" target="_blank" href="/<?php echo $this->module; ?>/Clientes/formulario/<?php echo $item['cliente_id']; ?>" title="<?php echo $ClientesModel->getOption('buttons', 'go'); ?>"><?php echo $ClientesModel->getOption('buttons', 'go'); ?></a> <?php echo $item['cliente']; ?></td>
                        <td><?php echo $item['categoria']; ?></td>
                        <td><?php echo $item['cidade']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php
else:
    ?>
    <div class="empty">
        Nenhum dado filtrado
    </div>
<?php endif; ?>