<div id="content">
    <div class="titulo">
        <div class="container_12">
            <div class="grid_12">
                <h1 class="sua_empresa">Serviços > Empresa</h1>
            </div>
        </div>
    </div>
    <div class="container_12" id="estacao_tratamento">
        <div class="grid_6 indent margem-b">
            <p>	Realizamos a Coleta, Transporte e Tratamento de efluentes domésticos, e também a coleta de efluentes provenientes de cabines de pintura, mediante a análise por laboratório especializado. Além disso, prestamos o serviço de transporte de efluentes industrias, para outras estações de tratamento.</p>
        </div>
        <div class="grid_6 indent">
            <p><img src="/css/images/empresa.png" /></p>
        </div>
        <div class="clearfix"></div>
        <div class="grid_12">
            <h2>A coleta da Cabine de Pintura</h2>
        </div>
        <div class="grid_6 indent margem-b">
            <p>Com o objetivo de assegurar a conservação dos ecossistemas, o Brasil possui uma legislação que regula o descarte de efluentes sobre os corpos d'água, limitando a carga poluidora lançada pelas indústrias. Em virtude disso, o gerenciamento da questão ambiental tem se tornado uma preocupação constante das empresas nos dias atuais, que necessitam proceder o tratamento dos seus efluentes antes de lançá-los nos meios hídricos. Uma das alternativas de maior confiabilidade é a terceirização do tratamento do efluente, que fica sob inteira responsabilidade da empresa contratada, que procederá o tratamento em sua estação própria, dentro dos parâmetros tecnológicos e legais apropriados, garantindo a segurança operacional do processo.</p>
        </div>
        <div class="grid_6 indent margem-b">
            <p>	Assim, a indústria geradora do efluente, ao delegar o tratamento para uma empresa especializada na atividade, obtém uma solução imediata para seu passivo ambiental, repassando a responsabilidade sobre todo seu efluente gerado. A terceirização do tratamento também é mais viável em termos técnicos e econômicos, pois, independentemente de seu porte e ramo de atividade, ela poderá focar seu capital econômico e humano apenas na sua atividade fim.</p>
        </div>
        <div class="clearfix"></div>
        <div class="grid_12 margem-t">
            <h2>Manutenção da Fossa Séptica e Filtro</h2>
        </div>
        <div class="grid_6 indent">
            <p>As fossas sépticas são as unidades de tratamento primário do esgoto doméstico, localizadas junto às edificações, e nas quais são feitas a separação e a transformação físico-química da matéria sólida contida no esgoto. Elas são necessárias, pois diminuem o lançamento de dejetos humanos diretamente na natureza (solo, rios, lagos) ou na rede de coleta pública, ajudando assim no combate a doenças, verminoses e endemias. Ela consiste de um tanque enterrado (que pode ser construído no local ou comprado pré-fabricado), que recebe o esgoto (dos vasos sanitários, bidês, chuveiros, ralos, tanques, etc...), retém a sua parte sólida e inicia o processo biológico de purificação da parte líquida.</p>
            <p>O efluente da fossa é lançado num filtro anaeróbico, onde ocorre o tratamento secundário do mesmo, pela decomposição dos poluentes por bactérias anaeróbicas, antes de ser lançado na rede pública. No entanto, à medida que a fossa séptica vai funcionando ocorre, no seu interior, um acúmulo de material sólido (lodo) que contém microrganismos patogênicos e que, quando em grande quantidade, podem obstruir totalmente a fossa e o filtro, reduzindo o tempo de retenção do efluente líquido dentro da fossa, tornando menos eficaz o tratamento primário. Além disso, pode provocar problemas de entupimentos nos encanamentos e tubulações.</p>
        </div>
        <div class="grid_6 indent">
            <p>	A limpeza da fossa séptica e do filtro deve ser efetuada a cada ano, de modo que não haja um acúmulo excessivo de lodo no seu interior, pois quando isso acontece, a fossa não consegue dar vazão ao lançamento de esgoto que ocorre, não retendo mais sua parte sólida. Assim, o esgoto in natura é lançado diretamente na rede de coleta sem passar pelo tratamento primário e as canalizações da residência podem ter problemas de entupimento com o refluxo do material acumulado. A limpeza da fossa séptica e do filtro deve ser feita de acordo com as disposições da NBR 7229/1993, por profissionais especializados que disponham de equipamentos adequados, para garantir o não-contato direto entre pessoas e lodo. Em nenhuma hipótese, sob pena de punições legais, o material retirado da fossa deve ser lançado em algum tipo de rio, lago ou canal de água pluvial. Ele deve ser retirado e conduzido até uma estação de tratamento.</p>
        </div>
    </div>
</div>
