<?php
if (!isset($this->noLayout)):
    $title = $this->model->getOption('title');
    if (!empty($this->data['cliente'])):
        $title .= ' (' . $this->data['cliente'] . ' | ' . $this->data['id'] . ' | ' . $this->data['data_emissao'] . ')';
    endif;
    echo $this->partial('partials/title.phtml', array(
        'title' => $title
    ));
endif;
if (!empty($this->data['cliente_id'])):
    ?>
    <div class="margemB">
        <a class="botao" href="/<?php echo $this->module; ?>/Clientes/formulario/<?php echo $this->data['cliente_id']; ?>" target="_blank">Ir para o Cliente</a>
    </div>
<?php endif; ?>
<div id="OrcamentosTabs">
    <ul>
        <li><a href="#Dados">Cliente</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Servicos/orcamento//<?php echo $this->data['id']; ?>">Serviços</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Orcamentos/configuracao//<?php echo $this->data['id']; ?>">Textos</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Orcamentos/visualizar//<?php echo $this->data['id']; ?>">Visualização</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Contas-Receber/orcamento//<?php echo $this->data['id']; ?>">Faturas</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Ordens-Servico/orcamento//<?php echo $this->data['id']; ?>">Ordens de Serviço</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Notas-Fiscais/orcamento//<?php echo $this->data['id']; ?>">Notas Fiscais</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Contratos/orcamento//<?php echo $this->data['id']; ?>">Contratos</a></li>
    </ul>
    <div id="Dados">
        <div class="grid_12">
            <?php
            if (isset($this->data['status']) && ($this->data['status'] == 3) && 1 != 1):
                $item = $this->model->adjustToView($this->data);
                ?>
                <table class="listagem">
                    <tr>
                        <th>Orçamento</th>
                        <td><?php echo $item['id']; ?></td>
                    </tr>
                    <tr>
                        <th>Empresa</th>
                        <td><?php echo $item['empresa']; ?></td>
                    </tr>
                    <tr>
                        <th>Cliente</th>
                        <td><?php echo $item['cliente']; ?></td>
                    </tr>
                    <tr>
                        <th>Vendedor</th>
                        <td><?php echo $item['fnome']; ?></td>
                    </tr>
                    <tr>
                        <th>Valor Fechado</th>
                        <td><?php echo $item['valor_total']; ?></td>
                    </tr>
                    <tr>
                        <th>Data de Emissão</th>
                        <td><?php echo $item['data_emissao']; ?></td>
                    </tr>
                </table>
                <div class="submodulo error ui-corner-all">Esse Orçamento já está concluído e não pode ser alterado!</div>
                <?php
            else:
                echo $this->form;
            endif;
            ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        $("#OrcamentosTabs").tabs({
            spinner: carregando,
            ajaxOptions: {
                error: function(xhr, status,index, anchor){
                    if(status == 'error'){
                        $(anchor.hash).html('Erro ao carregar o conteúdo');
                    }else{
                        $(anchor.hash).html(carregando);
                    }
                }
            }
<?php echo (empty($this->data['id'])) ? ",disabled: [1,2,3,4,5,6,7]" : ''; ?>
        });
    });
</script>