<div id="content">
    <div class="titulo">
        <div class="container_12">
            <div class="grid_12">
                <h1 class="estacao_tratamento">Informações > Estação de Tratamento</h1>
            </div>
        </div>
    </div>
    <div class="container_12" id="estacao_tratamento">
        <div class="grid_6 indent margem-b">
            <p>	A Estação de Tratamento de Efluentes da Acquasana foi implementada de acordo com as normas atuais vigentes. Nela são recebidos os efluentes de cabines de pinturas, vinícolas e assemelhados, de indústrias de pequeno e médio porte e efluentes domésticos, oriundos de fossas sépticas. A função da estação é tratar o efluente, emitindo laudos comprobatórios, solucionando assim os problemas de empresas que têm efluente estocado e/ou possuem um pequeno volume de efluentes, para os quais é inviável economicamente a instalação de uma planta individual.</p>
        </div>
        <div class="grid_6 indent">
            <p><img src="/css/images/estacao_tratamento.png" /></p>
        </div>
        <div class="grid_12 margem-b info_estacao">
            <h2>Efluentes Domésticos</h2>
            <h3>Etapas do Tratamento</h3>
            <div id="slide-domestico">
                <div class="grid_5 alpha">
                    <ul id="pagination-domestico">
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                    </ul>
                </div>
                <div class="grid_7 omega">
                    <ul class="indent" id="slider-domestico">
                        <li>
                            <h4>1. Armazenamento do Efluente</h4>
                            <p>O efluente a ser tratado é transportado por um caminhão tanque até uma área de descarga, para que o mesmo seja bombeado à um tanque de equalização, que se encontra protegido pela bacia de contenção. Bombas de alto rendimento fazem com que o efluente siga ao tratamento de forma adequada.</p>
                        </li>
                        <li>
                            <h4>2. Tratamento Biológico</h4>
                            <p>O tratamento biológico consiste em dois reatores anaeróbios UASB e três reatores aeróbios com sistema de aerador submerso. combinando-se a agitação do esgoto com a injeção de ar, desenvolve-se no tanque de aeração uma massa líquida de microorganismos chamada lodo ativado. Através do sistema de lodo ativado com aeração prolongada, a matéria orgânica (poluente) é consumida pelos microrganismos, promovendo assim, a eliminação dos compostos orgânicos contidos no efluente. O lodo gerado passa por um processo de decantação e, a seguir, é enviado a um filtro-prensa para desidratação e o clarificado é enviado ao corpo hídrico receptor.</p>
                        </li>
                        <li>
                            <h4>3. Descarte Final</h4>
                            <p>Todo lodo gerado no tratamento biológico é enviado para um tanque de armazenagem. Este é desaguado no filtro-prensa. O resíduo sólido formado é identificado, classificado e armazenado em recipientes apropriados e posteriormente enviado para descarte final em solo agrícola como fertilizante. O clarificado é lançado para o corpo hídrico receptor, atendendo aos padrões de emissão da Fepam.</p>
                        </li>
                        <li>
                            <h4>4. Controle Final</h4>
                            <p>No controle final, a qualidade do efluente tratado é medida e registrada continuamente de acordo com os dados de qualidade obtidos, o efluente tratado é direcionado para dois destinos: corpo hídrico receptor ou de volta ao processo de tratamento. Os parâmetros de todas as etapas intermediárias do tratamento são analisados em um laboratório credenciado pelo órgão fiscalizador, que presta assessoria à empresa. No laboratório são feitas as análises e exames fornecem dados para verificar a eficiência do tratamento. Ao final do tratamento, a Acquasana emite um laudo para o cliente, certificando o pelo tratamento realizado, no qual constam os padrões de emissão. Todo o processo de operação da E.T.E. é supervisionado por uma empresa terceirizada, isenta e altamente qualificada ambientalmente.</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="grid_12 info_estacao">
            <h2>Efluentes Industriais</h2>
            <h3>Etapas do Tratamento</h3>
            <div id="slide-industrial">
                <div class="grid_5 alpha">
                    <ul id="pagination-industrial">
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                    </ul>
                </div>
                <div class="grid_7 omega">
                    <ul class="indent" id="slider-industrial">
                        <li>
                            <h4>1. Armazenamento do Efluente</h4>
                            <p>O efluente a ser tratado é transportado por um caminhão tanque até uma área de descarga, para que o mesmo seja bombeado a um tanque de equalização, que se encontra protegido pela bacia de contenção. Bombas de alto rendimento fazem com que o efluente siga ao tratamento de forma adequada.</p>
                        </li>
                        <li>
                            <h4>2. Tratamento Físico-químico</h4>
                            <p>Este processo consiste na neutralização do efluente, com a adição de coagulantes e floculantes. Após a sedimentação, o lodo gerado é destinado a um tanque de decantação. O lodo resultante da decantação é enviado para um filtro prensa para desidratação. O efluente clarificado segue para o tanque de equalização para posterior tratamento secundário (tratamento biológico). Nosso reator é equipado com diversos instrumentos de medição e controle das variáveis de processo, controlando o volume, pH, nível de oxigênio dissolvido, etc, para otimização do processo e adequação ao efluente de entrada. No tratamento físico-químico podem ser realizadas as seguintes reações:</p>
                            <p>Neutralização e ajuste do pH, remoção de sólidos coloidais em suspensão e precipitação de metais pesados.</p>
                        </li>
                        <li>
                            <h4>3. Tratamento Biológico</h4>
                            <p>O tratamento biológico consiste em três reatores aeróbios com sistema de aerador submerso. Combinando-se a agitação do esgoto com a injeção de ar, desenvolve-se no tanque de aeração uma massa líquida de microorganismos chamada lodo ativado. Através do sistema de lodo ativado com aeração prolongada, a matéria orgânica (poluente) é consumida pelos microrganismos, promovendo assim, a eliminação dos compostos orgânicos contidos no efluente. O lodo gerado passa por um processo de decantação e, a seguir, é enviado a um filtro-prensa para desidratação e o clarificado é enviado ao corpo hídrico receptor.</p>
                        </li>
                        <li>
                            <h4>4. Controle Final</h4>
                            <p>No controle final, a qualidade do efluente tratado é medida e registrada continuamente. De acordo com os dados de qualidade obtidos, o efluente tratado é direcionado para dois destinos: corpo hídrico receptor ou de volta ao processo de tratamento. Os parâmetros de todas as etapas intermediárias do tratamento são analisados em um laboratório credenciado pelo órgão fiscalizador, que presta assessoria à empresa. No laboratório são feitas as análises e exames que fornecem dados para verificar a eficiência do tratamento. Ao final do tratamento, a Acquasana emite um laudo para o cliente, certificando-o pelo tratamento realizado, no qual constam os padrões de emissão. Todo o processo de operação da E.T.E. é supervisionado por uma empresa terceirizada, isenta e altamente qualificada ambientalmente.</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="/css/responsiveslides.css" />
<script src="/js/responsiveslides.min.js"></script>
<script>
    $(function() {
        $("#slider-domestico").responsiveSlides({
            auto: false,
            nav: true,
            prevText: "Etapa Anterior",
            nextText: "Próxima Etapa",
            pager: true,
            manualControls: '#pagination-domestico'
        });
        $("#slider-industrial").responsiveSlides({
            auto: false,
            nav: true,
            prevText: "Etapa Anterior",
            nextText: "Próxima Etapa",
            pager: true,
            manualControls: '#pagination-industrial'
        });
    });
</script>