<div id="content">
    <div class="titulo">
        <div class="container_12">
            <div class="grid_12">
                <h1 class="legislacao">Informações > Legislação</h1>
            </div>
        </div>
    </div>
    <div class="container_12">
        <div class="grid_12">
            <h2>Legislação Federal</h2>
            <ul class="listaPdfs">
                <li><a href="/legislacao/nbr_7229.pdf" title="Constituição Federal" target="_blank">NBR 7229</a></li>
                <li><a href="/legislacao/nbr_13969.pdf" title="Constituição Federal" target="_blank">NBR 13969</a></li>
                <li><a href="/legislacao/constituicao-federal.pdf" title="Constituição Federal" target="_blank">Constituição Federal</a></li>
                <li><a href="/legislacao/constituicao-federal-lei-9605.pdf" title="Constituição Federal Lei 9605" target="_blank">Constituição Federal Lei 9605</a></li>
                <li><a href="/legislacao/resolucao-20-conama.pdf" title="Resolução 20 CONAMA" target="_blank">Resolução 20 CONAMA</a></li>
                <li><a href="/legislacao/resolucao-303-conama.pdf" title="Resolução 303 CONAMA" target="_blank">Resolução 303 CONAMA</a></li>
                <li><a href="/legislacao/resolucao-357-conama.pdf" title="Resolução 357 CONAMA" target="_blank">Resolução 357 CONAMA</a></li>
                <li><a href="/legislacao/resolucao-375-conama.pdf" title="Resolução 375 CONAMA" target="_blank">Resolução 375 CONAMA</a></li>
                <li><a href="/legislacao/resolucao-420-antt.pdf" title="Resolução 420 ANTT" target="_blank">Resolução 420 ANTT</a></li>
            </ul>
            <h2>Legislação Estadual</h2>
            <ul class="listaPdfs">
                <li><a href="/legislacao/decreto-lei-9921.pdf" title="Decreto de Lei 9921" target="_blank">Decreto de Lei 9921</a></li>
                <li><a href="/legislacao/lei-estadual-9921.pdf" title="Lei Estadual 9921" target="_blank">Lei Estadual 9921</a></li>
                <li><a href="/legislacao/portaria-estadual-0589.pdf" title="Portaria Estadual 0589" target="_blank">Portaria Estadual 0589</a></li>
                <li><a href="/legislacao/resolucao-128-consema.pdf" title="Resolução 128 CONSEMA" target="_blank">Resolução 128 CONSEMA</a></li>
                <li><a href="/legislacao/resolucao-129-consema.pdf" title="Resolução 129 CONSEMA" target="_blank">Resolução 129 CONSEMA</a></li>
            </ul>
            <h2>Legislação Municipal</h2>
            <ul class="listaPdfs">
                <li><a href="/legislacao/lei-municipal-4000.pdf" title="Lei Municipal 4000" target="_blank">Lei Municipal 4000</a></li>
            </ul>
        </div>
    </div>
</div>