<?php
if (!isset($this->noLayout)):
    $title = $this->model->getOption('title');
    echo $this->partial('partials/title.phtml', array('title' => $title));
endif;
?>
<div id="ManutencaoCaminhaoTabs">
    <ul>
        <li><a href="#tabManutencaoCaminhao">Manutencao</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Pecas/manutencaocaminhao//<?php echo $this->data['id']; ?>">Peças</a></li>
        <!--<li><a href="/<?php echo $this->module; ?>/submodulo/ContasPagar/manutencaocaminhao//<?php echo $this->data['id']; ?>">Faturas</a></li>-->
    </ul>
    <div id="tabManutencaoCaminhao">
        <div class="grid_12">
            <?php
            echo $this->form;
            ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#ManutencaoCaminhaoTabs").tabs({
            spinner: carregando,
            ajaxOptions: {
                error: function (xhr, status, index, anchor) {
                    if (status == 'error') {
                        $(anchor.hash).html('Erro ao carregar o conteúdo');
                    } else {
                        $(anchor.hash).html(carregando);
                    }
                }
            }
<?php echo (empty($this->data['id'])) ? ",disabled: [1,2]" : ''; ?>
        });
    });
</script>