<div id="content" class="indent">
    <div class="titulo">
        <div class="container_12">
            <div class="grid_12">
                <h1 class="vantagens">Vantagens</h1>
            </div>
        </div>
    </div>
    <div class="container_12">
        <div class="grid_12">
            <h2>Cliente Doméstico</h2>
        </div>
        <div class="grid_6 margem-b">
            <p>Rapidez e agilidade na limpeza da fossa, do filtro e no recolhimento do efluente, evitando transtornos aos moradores e/ou usuários; prevenção de problemas com entupimento de tubulações e encanamentos; garantia da manutenção higiênica nos espaços, contribuindo para a qualidade de vida.</p>
        </div>
        <div class="grid_6 margem-b">
            <p>A garantia de um destino adequado aos efluentes de sua fossa séptica e a certeza de estar tomando uma atitude ecologicamente correta, contribuindo para a manutenção do sistema de saneamento da cidade e, consequentemente, para a preservação do meio-ambiente e da saúde pública.</p>
        </div>
        <div class="grid_12 margem-t">
            <h2>Cliente Industrial</h2>
        </div>
        <div class="grid_6 margem-b">
            <p>Economia de investimentos, pois a indústria não precisa arcar com os custos de planejar, implantar e gerir uma estação de tratamento própria; não precisa dispor de uma área para construir sua estação de tratamento, nem absorver os custos com funcionários especializados, podendo assim se concentrar nas suas atividades; redução de custos operacionais, pois a indústria repassa a responsabilidade do tratamento e descarte final do lodo, arcando somente com o custo da quantidade de efluente tratado;</p>
        </div>
        <div class="grid_6 margem-b">
            <p>	 A qualidade do trabalho e tratamento: o efluente industrial tratado pela estação passa por um tratamento primário e secundário que aprimora as características do efluente o que, via de regra, não acontece nas estações de tratamento próprias das empresas; a garantia que seu efluente terá um destino final adequado, prevenindo-se assim de qualquer problema legal relativo à responsabilidade ambiental e a redução no impacto do seu processo produtivo na natureza, o que agrega valor ao produto em uma economia preocupada com o planeta.</p>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="cinza indent" style="padding-bottom: 15px">
    <div class="container_12">
        <div class="grid_6">
            <h2>Garantia de Qualidade</h2>
            <p>A Acquasana tem como proposta prestar um serviço de qualidade aos seus clientes, baseando suas ações nas normas vigentes na legislação ambiental e nos mais rigorosos critérios científicos relativos ao tratamento de efluentes e descarte de resíduos.</p>
            <p>O processo de trabalho da Acquasana elegeu como estratégia de ação, conciliar a limpeza de fossas sépticas e filtros, o transporte dos efluentes retirados nesta limpeza, e daqueles provenientes das cabines de pintura e outros processos industriais, o seu tratamento e, finalmente, o seu descarte. Encarregando-se de todo o ciclo envolvido no manejo do efluente, podendo fornecer aos clientes a garantia de um destino final adequado para o mesmo.</p>
        </div>
        <div class="grid_6">
            <h2>Responsabilidade Ambiental</h2>
            <p>A filosofia da Acquasana é atuar no mercado de uma forma ecologicamente correta, contribuindo para a preservação do meio ambiente. Com essa atitude a Acquasana faz a sua parte, pensando na natureza e nas futuras gerações, colaborando e incentivando para que seus clientes também façam a sua parte.</p>
            <p>Como parte desse incentivo é indicada a limpeza da fossa séptica (remoção do excesso de lodo), que é fundamental para o seu perfeito funcionamento. Fazendo periodicamente, além de atender as normas vigentes no Brasil, contribuirá para a prevenção de obstruções nas redes de esgoto prediais, mantendo funcional o sistema de tratamento de efluentes adotado pelo município.</p>
        </div>
    </div>
</div>