<div class="grid_12">
    <?php
    if (!($this->noLayout)):
        echo $this->partial('partials/title.phtml', array(
            'title' => $this->model->getOption('title')
        ));
    endif;
    if (!empty($this->items)):
        ?>
        <table class="listagem">
            <thead>
                <tr class="ui-widget-header">
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>Código</th>
                    <th>Data da Coleta</th>
                    <th>Valor</th>
                    <th>Desconto</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $total = 0;
                foreach ($this->items AS $item):
                    $total += $item['saldo'];
                    $item = $this->model->adjustToView($item);
                    ?>
                    <tr class="<?php echo $item['class']; ?>">
                        <!--
                        <td align="center"><button class="btEditar <?php echo $this->controller; ?>" source="<?php echo $item['id']; ?>"><?php echo $this->model->getOption('buttons', 'edit'); ?></button></td>
                        <td align="center"><button class="btExcluir <?php echo $this->controller; ?>" source="<?php echo $item['id']; ?>"><?php echo $this->model->getOption('buttons', 'delete'); ?></button></td>
                        <td align="center"><a class="btVisualizar" href="/<?php echo $this->module; ?>/print/<?php echo $this->controller; ?>/visualizar/<?php echo $item['id']; ?>" target="_blank"><?php echo $this->model->getOption('buttons', 'view'); ?></a></td>
                        -->
                        <td align="center"><a class="btEditar <?php echo $this->controller; ?>" href="/<?php echo $this->module . '/' . $this->controller . '/formulario/' . $item['id']; ?>" source="<?php echo $item['id']; ?>"><?php echo $this->model->getOption('buttons', 'edit'); ?></a></td>
                        <td align="center"><a class="btExcluir <?php echo $this->controller; ?>" href="/<?php echo $this->module . '/' . $this->controller . '/excluir/' . $item['id']; ?>" source="<?php echo $item['id']; ?>"><?php echo $this->model->getOption('buttons', 'delete'); ?></a></td>
                        <td align="center"><a class="btVisualizar" href="/<?php echo $this->module; ?>/print/<?php echo $this->controller; ?>/visualizar/<?php echo $item['id']; ?>" target="_blank"><?php echo $this->model->getOption('buttons', 'view'); ?></a></td>
                        <td align="center"><?php echo $item['orcamento_id']; ?>.<?php echo $item['sequencial']; ?></td>
                        <td align="center"><?php echo $item['data_coleta']; ?></td>
                        <td class="valor"><?php echo $item['valor']; ?></td>
                        <td class="valor"><?php echo $item['desconto']; ?></td>
                        <td class="valor"><?php echo $item['saldo']; ?></td>
                    </tr>
                    <?php
                endforeach;
                ?>
            </tbody>
            <tfoot>
                <tr class="ui-widget-header">
                    <th colspan="7">Total</th>
                    <td><?php echo WS_Money::adjustToView($total); ?></td>
                </tr>
            </tfoot>
        </table>
        <?php
    else:
        echo $this->partial('partials/empty.phtml', array(
            'message' => $this->model->getOption('messages', 'empty')
        ));
    endif;
    if ($this->noLayout):
        ?>
        <!--
            <div id="<?php echo $this->controller; ?>Modal" class="modal" title="<?php echo $this->model->getOption('title'); ?>"></div>
            <script type="text/javascript" src="/js/submodulo.js"> </script>
            <script type="text/javascript">
                $(function(){
                    $().submodulo({
                        controller: '<?php echo $this->controller; ?>',
                        module: '<?php echo $this->module; ?>',
                        tab: '#OrcamentosTabs',
                        modal: '#<?php echo $this->controller; ?>Modal',
                        form: '#<?php echo $this->form->getId(); ?>',
                        parent_id : '<?php echo (!empty($this->data['parent_id'])) ? $this->data['parent_id'] : ''; ?>'
                    });
                });
            </script>
        -->
    <?php endif; ?>
</div>