<?php
if (!isset($this->noLayout)):
  $title = $this->model->getOption('title');
  if (!empty($this->data['razao_social'])):
    $title .= ' (' . $this->data['razao_social'] . ')';
  endif;
  echo $this->partial('partials/title.phtml', array(
    'title' => $title
  ));
endif;
if (isset($this->data['id'])):
  ?>
  <a class="botao margem-b"
     href="/<?php echo $this->module; ?>/print/Relatorio-Clientes/etiquetas?cliente_id[]=<?php echo $this->data['id']; ?>"
     target="_blank">Imprimir Etiqueta</a>
  <?php if (!empty($this->enderecos)): ?>
  |
  <select name="endereco_ar_id" id="endereco_ar_id">
    <?php foreach ($this->enderecos AS $id => $endereco): ?>
      <option value="<?php echo $id; ?>"><?php echo $endereco; ?></option>
    <?php endforeach; ?>
  </select>
  <button type="button" id="imprimeAR">Imprimir AR</button>
  <script>
  $(function () {
    $("#imprimeAR").die('click').unbind('click').click(function () {
      var endereco = $('#endereco_ar_id').val();
      var url = '/<?php echo $this->module; ?>/print/<?php echo $this->controller; ?>/ar/<?php echo $this->data['id']; ?>/' + endereco;
      window.open(url);
    });
  });
  </script>
<?php
endif;
endif;
?>
<div id="ClientesTabs">
  <ul>
    <li><a href="#Dados">Dados</a></li>
    <li><a href="/<?php echo $this->module; ?>/submodulo/Clientes-Enderecos/cliente//<?php echo $this->data['id']; ?>">End.</a>
    </li>
    <li><a href="/<?php echo $this->module; ?>/submodulo/Clientes-Telefones/cliente//<?php echo $this->data['id']; ?>">Tel.</a>
    </li>
    <li><a
        href="/<?php echo $this->module; ?>/submodulo/Clientes-Crm/cliente//<?php echo $this->data['id']; ?>">Atend.</a>
    </li>
    <li><a href="/<?php echo $this->module; ?>/submodulo/Orcamentos/cliente//<?php echo $this->data['id']; ?>">Orçamentos</a>
    </li>
    <li><a href="/<?php echo $this->module; ?>/submodulo/Ordens-Servico/cliente//<?php echo $this->data['id']; ?>">Ordens
        de Serviço</a></li>
    <li><a href="/<?php echo $this->module; ?>/submodulo/Contas-Receber/cliente//<?php echo $this->data['id']; ?>">Faturas</a>
    </li>
    <li><a
        href="/<?php echo $this->module; ?>/submodulo/Contratos/cliente//<?php echo $this->data['id']; ?>">Contratos</a>
    </li>
    <li><a
        href="/<?php echo $this->module; ?>/submodulo/Certificados/cliente//<?php echo $this->data['id']; ?>">Cert.</a>
    </li>
    <li><a
        href="/<?php echo $this->module; ?>/submodulo/Notas-Fiscais/cliente//<?php echo $this->data['id']; ?>">N.F.</a>
    </li>
    <li><a href="/<?php echo $this->module; ?>/submodulo/Cte/cliente//<?php echo $this->data['id']; ?>">CT-e</a></li>
    <li><a href="/<?php echo $this->module; ?>/submodulo/Cte-Acqualife/cliente//<?php echo $this->data['id']; ?>">CT-e
        Acqualife</a></li>
    <li><a href="/<?php echo $this->module; ?>/submodulo/Cte-Acquaservicos/cliente//<?php echo $this->data['id']; ?>">CT-e
        Acquaserviços</a></li>
    <li><a href="/<?php echo $this->module; ?>/submodulo/Clientes-Arquivos/cliente//<?php echo $this->data['id']; ?>">Arquivos</a>
    </li>
  </ul>
  <div id="Dados">
    <div class="grid_12">
      <?php echo $this->form; ?>
    </div>
  </div>
</div>
<script type="text/javascript">
$(function () {
  $("#ClientesTabs").tabs({
    spinner: carregando,
    ajaxOptions: {
      error: function (xhr, status, index, anchor) {
        if (status == 'error') {
          $(anchor.hash).html('Erro ao carregar o conteúdo');
        } else {
          $(anchor.hash).html(carregando);
        }
      }
    }
    <?php echo (empty($this->data['id'])) ? ', disabled: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]' : ''; ?>
  });
  <?php if ((isset($this->data['documento_tipo']) && $this->data['documento_tipo'] == 2)): ?>
  $("#documento").unmask();
  $("#documento").mask("999.999.999-99");
  <?php else: ?>
  $("#documento").unmask();
  $("#documento").mask("99.999.999/9999-99");
  <?php endif; ?>
  $("#documento_tipo").change(function () {
    mudaMascara();
  });
});

function mudaMascara () {
  var documento = $("#documento").select().val();
  var selecionado = $("#documento_tipo").select().val();
  if (selecionado == 2) {
    $("#documento").unmask();
    $("#documento").mask("999.999.999-99");
    $("#documento").val(documento);
  } else {
    $("#documento").unmask();
    $("#documento").mask("99.999.999/9999-99");
    $("#documento").val(documento);
  }
}

</script>
