<h2><?php echo $this->model->getOption('title'); ?></h2>
<?php
if ($this->csv) :
    ?>
    <script>
        $(function () {
            $.jGrowl("Verifique o bloqueio de pop-ups!", {theme: "warning", life: 10000});
        });
        window.open('/uploads/relatorios/<?php echo $this->csv; ?>');
    </script>
    <?php
endif;
?>
<div class="hidden">
    <form method="post">
        <table class="listagem">
            <tr>
                <th colspan="4">Data de Vencimento</th>
                <th rowspan="12">
                    <button type="submit">Filtrar</button><br /><br />
                    <button type="button" id="btImprimir">Imprimir</button><br /><br />
                    <button type="button" id="btExportarCSV">Exportar em CSV</button>
                    <input type="checkbox" class="invisivel" name="gera_csv" id="gera_csv" />
                </th>
            </tr>
            <tr>
                <th>Inicial</th>
                <td><input type="text" name="data_inicial" value="<?php echo $this->data['data_inicial']; ?>" class="filter date" /></td>
                <th>Final</th>
                <td><input type="text" name="data_final" value="<?php echo $this->data['data_final']; ?>" class="filter date" /></td>
            </tr>
            <tr>
                <th colspan="4">Data de Pagamento</th>
            </tr>
            <tr>
                <th>Inicial</th>
                <td><input type="text" name="data_inicial_pago" value="<?php echo $this->data['data_inicial_pago']; ?>" class="filter date" /></td>
                <th>Final</th>
                <td><input type="text" name="data_final_pago" value="<?php echo $this->data['data_final_pago']; ?>" class="filter date" /></td>
            </tr>
            <tr>
                <th colspan="4">Data de Lançamento</th>
            </tr>
            <tr>
                <th>Inicial</th>
                <td><input type="text" name="data_inicial_lancamento" value="<?php echo $this->data['data_inicial_lancamento']; ?>" class="filter date" /></td>
                <th>Final</th>
                <td><input type="text" name="data_final_lancamento" value="<?php echo $this->data['data_final_lancamento']; ?>" class="filter date" /></td>
            </tr>
            <tr>
                <th>Status</th>
                <td><select name="status">
                        <option value="">Todos</option>
                        <option value="vencidas" <?php echo ($this->data['status'] == 'vencidas') ? 'selected="selected"' : ''; ?>>Atrasadas</option>
                        <option value="aberto" <?php echo ($this->data['status'] == 'aberto') ? 'selected="selected"' : ''; ?>>Aberto</option>
                        <option value="pagas" <?php echo ($this->data['status'] == 'pagas') ? 'selected="selected"' : ''; ?>>Pagas</option>
                    </select></td>
                <th>Empresa</th>
                <td><select name="empresa_id">
                        <option value="">Todas</option>
                        <?php
                        $EmpresasModel = new Empresas_Model();
                        foreach ($EmpresasModel->fetchPair() as $id => $razao_social) :
                            ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['empresa_id'] == $id) ? 'selected="selected"' : ''; ?>><?php echo $razao_social; ?></option>
                        <?php endforeach; ?>
                    </select></td>
            </tr>
            <tr>
                <th>Categoria</th>
                <td><select name="categoria_id">
                        <option value="">Todas</option>
                        <?php
                        $ContasPagarCategoriasModel = new ContasPagarCategorias_Model();
                        foreach ($ContasPagarCategoriasModel->fetchPair() as $id => $categoria) :
                            ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['categoria_id'] == $id) ? 'selected="selected"' : ''; ?>><?php echo $categoria; ?></option>
                        <?php endforeach; ?>
                    </select></td>
                <th>Conta Fixa</th>
                <td><select name="conta_fixa">
                        <option value="">Todas</option>
                        <option value="1" <?php echo ($this->data['conta_fixa'] == 1) ? 'selected="selected"' : ''; ?>>Fixa</option>
                        <option value="2" <?php echo ($this->data['conta_fixa'] == 2) ? 'selected="selected"' : ''; ?>>Variável</option>
                    </select></td>
            </tr>
            <tr>
                <th>Categoria de Fornecedor</th>
                <td><select name="fornecedor_categoria_id">
                        <option value="">Todas</option>
                        <?php
                        $FornecedoresCategoriasModel = new FornecedoresCategorias_Model();
                        foreach ($FornecedoresCategoriasModel->fetchPair() AS $id => $categoria) :
                            ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['fornecedor_categoria_id'] == $id) ? 'selected="selected"' : ''; ?>><?php echo $categoria; ?></option>
                        <?php endforeach; ?>
                    </select></td>
                <th>Fornecedor</th>
                <td><select name="fornecedor_id">
                        <option value="">Todas</option>
                        <?php
                        $FornecedoresModel = new Fornecedores_Model();
                        foreach ($FornecedoresModel->fetchPair() as $id => $razao_social) :
                            ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['fornecedor_id'] == $id) ? 'selected="selected"' : ''; ?>><?php echo $razao_social; ?></option>
                        <?php endforeach; ?>
                    </select></td>
            </tr>
            <tr>
                <th>Forma de Pagamento</th>
                <td colspan="3"><select name="forma_pagamento_id">
                        <option value="">Todas</option>
                        <?php
                        $FormasPagamentoModel = new FormasPagamento_Model();
                        foreach ($FormasPagamentoModel->fetchPair() as $id => $forma_pagamento) :
                            ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['forma_pagamento_id'] == $id) ? 'selected="selected"' : ''; ?>><?php echo $forma_pagamento; ?></option>
                        <?php endforeach; ?>
                    </select></td>
            </tr>
            <?php
            $ordem = array(
                'cp.data_pagamento' => 'Data de Pagamento',
                'cp.data_vencimento' => 'Data de Vencimento',
                'fp.forma_pagamento' => 'Forma de Pagamento',
                'empresa' => 'Empresa',
                'fornecedor' => 'Fornecedor',
            );
            $ordem_tipo = array(
                'ASC' => 'Crescente',
                'DESC' => 'Decrescente',
            );
            ?>
            <tr>
                <th>Ordenação</th>
                <td>
                    <select name="ordem">
                        <?php foreach ($ordem AS $id => $nome): ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['ordem'] == $id) ? 'selected="selected"' : ''; ?>><?php echo $nome; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <th>Tipo de Ordenação</th>
                <td>
                    <select name="ordem_tipo">
                        <?php foreach ($ordem_tipo AS $id => $nome): ?>
                            <option value="<?php echo $id; ?>" <?php echo ($this->data['ordem_tipo'] == $id) ? 'selected="selected"' : ''; ?>><?php echo $nome; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
        </table>
    </form>
</div>
<?php if (!empty($this->items)): ?>
    <div class="print">
        <table class="listagem">
            <thead>
                <tr>
                    <th>Status</th>
                    <th colspan="2">Vencimento</th>
                    <th colspan="2">Pagamento</th>
                    <th>Cat. Fornec.</th>
                    <th>Fornecedor</th>
                    <th>Cat. Conta</th>
                    <th>Empresa</th>
                    <th>Forma Pag.</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $valorTotal = 0;
                $valorPago = 0;
                foreach ($this->items AS $item):
                    $valorTotal+= $item['valor'];
                    $valorPago+= $item['valor_pago'];
                    $item = $this->model->adjustToView($item);
                    ?>
                    <tr>
                        <td align="center"><a class="buttonLink hidden" target="_blank" href="/<?php echo $this->module; ?>/Contas-Pagar/formulario/<?php echo $item['id']; ?>" title="<?php echo $this->model->getOption('buttons', 'go'); ?>"><?php echo $this->model->getOption('buttons', 'go'); ?></a> <?php echo $item['status']; ?></td>
                        <td><?php echo $item['data_vencimento']; ?></td>
                        <td class="valor"><?php echo $item['valor']; ?></td>
                        <td>
                            <?php echo (($item['data_vencimento'] != $item['data_pagamento'])) ? '<b><i>' . $item['data_pagamento'] . '</i></b>' : $item['data_pagamento']; ?>
                        </td>
                        <td class="valor">
                            <?php echo (($item['valor'] != $item['valor_pago'])) ? '<b><i>' . $item['valor_pago'] . '</i></b>' : $item['valor_pago']; ?>
                        </td>
                        <td><?php echo $item['categoria_fornecedor']; ?></td>
                        <td><a class="buttonLink hidden" target="_blank" href="/<?php echo $this->module; ?>/Fornecedores/formulario/<?php echo $item['fornecedor_id']; ?>" title="<?php echo $FornecedoresModel->getOption('buttons', 'go'); ?>"><?php echo $FornecedoresModel->getOption('buttons', 'go'); ?></a> <?php echo $item['fornecedor']; ?></td>
                        <td><?php echo $item['categoria']; ?></td>
                        <td><?php echo $item['empresa']; ?></td>
                        <td><?php echo $item['forma_pagamento']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <th>Total Gerado</th>
                    <th colspan="4"><?php echo WS_Money::adjustToView($valorTotal); ?></th>
                    <th>Total Pago</th>
                    <th colspan="4"><?php echo WS_Money::adjustToView($valorPago); ?></th>
                </tr>
            </tfoot>
        </table>
    </div>
<?php else: ?>
    <div class="empty">
        Nenhum dado filtrado
    </div>
<?php endif; ?>