<?php
if (!isset($this->noLayout)):
    $title = $this->model->getOption('title');
    if (!empty($this->data['nome'])):
        $title .= ' (' . $this->data['nome'] . ')';
    endif;
    echo $this->partial('partials/title.phtml', array(
        'title' => $title
    ));
endif;
$item = $this->model->adjustToView($this->data);
?>
<div id="ProjetosTabs">
    <ul>
        <li><a href="#Dados">Projeto</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Projetos-Crm/projeto//<?php echo $this->data['id']; ?>">Atendimentos/Atividades</a></li>
    </ul>
    <div id="Dados">
        <div class="grid_12">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        $("#ProjetosTabs").tabs({
            spinner: carregando,
            ajaxOptions: {
                error: function(xhr, status, index, anchor) {
                    if (status == 'error') {
                        $(anchor.hash).html('Erro ao carregar o conteúdo');
                    } else {
                        $(anchor.hash).html(carregando);
                    }
                }
            }
<?php echo (empty($this->data['id'])) ? ",disabled: [1,2]" : ''; ?>
        });
    });
</script>