<?php
if (!($this->noLayout)):
    echo $this->partial('partials/title.phtml', array(
        'title' => $this->model->getOption('title')
    ));
endif;
if (isset($this->model->_addButton)):
    echo $this->partial('partials/btAdicionar.phtml', array(
        'controller' => $this->controller,
        'module' => $this->module,
        'message' => $this->model->getOption('buttons', 'add')
    ));
endif;
?>
<form method="post" action="/<?php echo $this->module; ?>/<?php echo $this->controller; ?>/excluir" class="formListagem">
    <?php if (!empty($this->items)): ?>
        <table class="listagem" id="ContasPagarListagem">
            <thead>
                <tr>
                    <?php echo $this->partial('partials/btExcluir.phtml', array('controller' => $this->controller, 'model' => $this->model)); ?>
                    <th></th>
                    <th></th>
                    <th>Categoria</th>
                    <th>Fornecedor</th>
                    <th>Vencimento</th>
                    <th>Valor</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->items AS $item):
                    $item = $this->model->adjustToView($item);
                    ?>
                    <tr class="<?php echo $item['class']; ?>">
                        <?php echo $this->partial('partials/itemDel.phtml', array('item' => $item)); ?>
                        <?php echo $this->partial('partials/btEditar.phtml', array('controller' => $this->controller, 'model' => $this->model, 'item' => $item)); ?>
                        <td><a href="/<?php echo $this->module; ?>/<?php echo $this->controller; ?>/pagar/<?php echo $item['id']; ?>" class="btPagar" title="<?php echo $this->model->getOption('buttons', 'pay'); ?>"><?php echo $this->model->getOption('buttons', 'pay'); ?></a></td>
                        <td><?php echo $item['categoria']; ?></td>
                        <td><?php echo $item['fornecedor']; ?></td>
                        <td><?php echo $item['data_vencimento']; ?></td>
                        <td class="valor"><?php echo $item['valor']; ?></td>
                        <td><?php echo $item['status']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php
    else:
        echo $this->partial('partials/empty.phtml', array(
            'message' => $this->model->getOption('messages', 'empty')
        ));
    endif;
    ?>
</form>
<script type="text/javascript">
    $(function(){
        $('#ContasPagarListagem').dataTable({
            "oLanguage": { "sUrl": "/js/dataTables/pt_BR.txt" },
            "bJQueryUI": true,
            "aaSorting": [[7,"asc"], [5,"asc"]],
            "aoColumns":[
                {"bSortable": false},
                {"bSortable": false},
                {"bSortable": false},
                {"bSortable": true},
                {"bSortable": true},
                {"bSortable": true},
                {"bSortable": true},
                {"bSortable": true}
            ]
        });
    });
</script>