<h2><?php echo $this->model->getOption('title'); ?></h2>
<div class="hidden">
    <form method="post" id="Form_Relatorio_Notas_Fiscais">
        <table class="listagem">
            <tr>
                <th>Data Inicial</th>
                <th><input type="text" name="data_inicial" value="<?php echo $this->data['data_inicial']; ?>" class="filter date" /></th>
                <th>Data Final</th>
                <th><input type="text" name="data_final" value="<?php echo $this->data['data_final']; ?>" class="filter date" /></th>
                <th rowspan="4"><button type="submit">Filtrar</button></th>
                <th rowspan="4"><button type="button" id="btImprimir">Imprimir</button></th>
            </tr>
        </table>
    </form>
</div>
<?php if (!empty($this->items)): ?>
    <div class="print">
        <table class="listagem">
            <thead>
                <tr>
                    <th>Número</th>
                    <th>Cliente</th>
                    <th>Data de Emissão</th>
                    <th>Valor</th>
                    <th>Valor Retido</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $OrcamentosModel = new Orcamentos_Model();
                $total['valor'] = 0;
                $total['retido'] = 0;
                foreach ($this->items AS $item):
                    $total['valor'] += $item['valor'];
                    $total['retido'] += $item['valor_retido'];
                    $item = $this->model->adjustToView($item);
                    ?>
                    <tr>
                        <td align="center"><?php echo $item['numero']; ?></td>
                        <td align="center"><?php echo $item['cliente']; ?></td>
                        <td align="center"><?php echo $item['data_emissao']; ?></td>
                        <td align="center"><?php echo $item['valor']; ?></td>
                        <td align="center"><?php echo $item['valor_retido']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="3">Total</th>
                    <td align="center"><?php echo WS_Money::adjustToView($total['valor']); ?></td>
                    <td align="center"><?php echo WS_Money::adjustToView($total['retido']); ?></td>
                </tr>
            </tfoot>
        </table>
    </div>
    <?php
else:
    ?>
    <div class="error">
        Nenhum dado filtrado
    </div>
<?php endif; ?>